const shortcuts_admin = [{'btn': ''},
    {'btn-accept': ''},
    {'btn-cancel': ''},
    {'btn-create': ''},
    {'r-container-list': 'justify-center flex align-center p-6 h-[45-rem]'},
    {'r-container-page': 'justify-center p-6 w-full h-[45-rem]'},
    {'r-container-form': 'bg-white dark:bg-slate-800 shadow overflow-hidden sm:rounded-lg'},
    {'r-footer-form': 'relative flex items-start'},
    {'r-footer-button-form': 'flex-1 lg:justify-end align-end items-end lg:mt-none md:mt-10 sm:w-full sm:justify-center'},
    {'btn-delete': '!cursor-pointer mr-3 !bg-red-800 hover:bg-red-600 hover:disabled:bg-gray-100 disabled:!bg-white disabled:!text-gray-500 disabled:border-solid disabled:border-[1px]'},
    {'r-breadcumbs': 'bg-white px-5 py-5 rounded-md shadow-sm mx-5 mt-[3.5rem]'},
    {'r-header-modal': 'text-black'},
    {'r-close-icon': 'i-heroicons:x-mark text-black'},
    {'r-loading-default': 'i-svg-spinners:6-dots-scale text-primary-800 text-[3rem]'},
    {'ctn-input': 'w-full border-thin ring-1 ring-primary-300'},
    {'grid-input': 'xl:col-span-1  lg:col-span-2 md:col-span-2 sm:col-span-4 xs:col-span-4'},
    {'btn-rg': '!font-bold press r-button outline-none border-none relative select-none overflow-hidden group inline-flex items-center justify-center !outline-none ring-0 rounded-md transition-all duration-100 cursor-pointer r-button-filled-primary default bg-primary-600 active:!bg-primary-600 text-white hover:bg-primary-700 dark:bg-primary-600 dark:hover:bg-primary-500 dark:active:!bg-primary-600 !rounded-full text-sm font-medium px-4 py-2 h-9 bg-gradient-to-r from-primary-500 to-indigo-600 hover:from-primary-600 hover:to-indigo-700 text-xl font-bold px-10 !py-7 transform transition hover:scale-110 duration-300 ease-in-out'},
    {'icon-btn': 'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600'},
    {'badge-primary': 'bg-primary-50 text-primary-800 text-xs font-medium me-2 px-2.5 py-0.5 w-30 rounded dark:bg-blue-900 dark:text-blue-300'},]
export default shortcuts_admin
